---
collections:
  - name: ansible.netcommon
    version: 6.0.0
    source: https://galaxy.ansible.com
  - name: cisco.ios
    version: 6.1.2
    source: https://galaxy.ansible.com
  - name: community.routeros
    version: 2.11.0
    source: https://galaxy.ansible.com
