---
collections:
  - name: ansible.netcommon
    version: 6.1.1
    source: https://galaxy.ansible.com
  - name: cisco.ios
    version: 8.0.0
    source: https://galaxy.ansible.com
  - name: community.routeros
    version: 2.15.0
    source: https://galaxy.ansible.com
