---
all:
  vars:
    syslog_server: 192.168.0.254
    ntp_server: 192.168.9.1

mikrotik:
  hosts:
    steffy:
      ansible_host: 192.168.5.1 # connect over either SSH or API 8729
      user: ansible
      ansible_user: "{{ user }}"
      ansible_pass: "{{ ansible_ssh_pass }}"

switch:
  hosts:
    cosmo:
      ansible_host: 192.168.9.10
      ansible_user: ansible
      ansible_ssh_pass:
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: ios
      ansible_become_method: enable
      ansible_libssh_host_key_checking: false

unifi:
  hosts:
    controller:
      ansible_host: https://unifi.chickenwaffles.net
      ansible_user: ansible
      ansible_password:
      identity: VOID Network
      inform_host: 192.168.0.243 # IP of unifi loadbalancer for APs to register against
      wireless_networks:
        - name: THE-VOID
          password:
          vlan_name: USERS
          vlan: 5
          vlan_dhcp: 192.168.5.1
          client_isolation: false
          wlan_bands: ["2g", "5g"]
        - name: THE-VOID-GUEST
          password:
          vlan_name: GUEST
          vlan: 6
          vlan_dhcp: 192.168.6.1
          client_isolation: false
          wlan_bands: ["2g", "5g"]
        - name: THE-VOID-IOT
          password:
          vlan_name: IOT
          vlan: 7
          vlan_dhcp: 192.168.7.1
          client_isolation: true
          wlan_bands: ["2g"]
