---
- name: Get BridgeInterface name
  community.routeros.api_info:
    path: interface bridge
  register: bridge_interface

# - name: Show bridge interface
#  ansible.builtin.debug:
#    var: bridge_interface.result

- name: Set BridgeInterface fact
  ansible.builtin.set_fact:
    bridge_name: "{{ bridge_interface.result[0].name }}"

- name: Add VLANS
  community.routeros.api_modify:
    path: interface vlan
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    data:
      - name: USER
        vlan-id: 5
        interface: "{{ bridge_name }}"
      - name: GUEST
        vlan-id: 6
        interface: "{{ bridge_name }}"
      - name: IOT
        vlan-id: 7
        interface: "{{ bridge_name }}"
      - name: NTWK
        vlan-id: 9
        interface: "{{ bridge_name }}"
      - name: INFRA
        vlan-id: 99
        interface: "{{ bridge_name }}"

# VLANS
## VLAN 5 - USER - 192.168.5.0/24
## VLAN 6 - GUEST - 192.168.6.0/24, ntp, dns, 10-50
## VLAN 7 - IOT - 192.168.7.0/24
## VLAN 9 - NTWK - 192.168.9.0/24
## VLAN 99 - INFRA - 192.168.0.0/24 - ntp,dns, 30-70

# LAGG

# VPN - wireguard

# Set port 1 as internet
# Set port 3 as VLAN 5
# set port 4 as VLAN 9
# set port 5 as VLAN 99
