---
- name: Create bridge
  community.routeros.api_modify:
    path: interface bridge
    data:
      - name: local
        frame-types: admit-only-vlan-tagged
        ingress-filtering: true
        vlan-filtering: true

- name: Get BridgeInterface name
  community.routeros.api_info:
    path: interface bridge
  register: bridge_interface

- name: Set BridgeInterface fact
  ansible.builtin.set_fact:
    bridge_name: "{{ bridge_interface.result[0].name }}"

- name: Configure Bridge Ports
  community.routeros.api_modify:
    path: interface bridge port
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    data:
      - bridge: "{{ bridge_name }}"
        interface: ether2
        ingress-filtering: true
        frame-types: admit-only-vlan-tagged

- name: Add VLANS
  community.routeros.api_modify:
    path: interface vlan
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    data:
      - name: USER
        vlan-id: 5
        interface: "{{ bridge_name }}"
      - name: GUEST
        vlan-id: 6
        interface: "{{ bridge_name }}"
      - name: IOT
        vlan-id: 7
        interface: "{{ bridge_name }}"
      - name: NTWK
        vlan-id: 9
        interface: "{{ bridge_name }}"
      - name: INFRA
        vlan-id: 99
        interface: "{{ bridge_name }}"

- name: Configure IP address on interfaces
  community.routeros.api_modify:
    path: ip address
    data:
      - interface: USER
        address: 192.168.5.1/24
        network: 192.168.5.0
      - interface: GUEST
        address: 192.168.6.1/24
        network: 192.168.6.0
      - interface: IOT
        address: 192.168.7.1/24
        network: 192.168.7.0
      - interface: NTWK
        address: 192.168.9.1/24
        network: 192.168.9.0
      - interface: INFRA
        address: 192.168.0.1/24
        network: 192.168.0.0

- name: VLAN Tag Interfaces
  community.routeros.api_modify:
    path: interface bridge vlan
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    data:
      - bridge: "{{ bridge_name }}"
        tagged: "{{ bridge_name }},ether2"
        vlan-ids: 5
      - bridge: "{{ bridge_name }}"
        tagged: "{{ bridge_name }},ether2"
        vlan-ids: 6
      - bridge: "{{ bridge_name }}"
        tagged: "{{ bridge_name }},ether2"
        vlan-ids: 7
      - bridge: "{{ bridge_name }}"
        tagged: "{{ bridge_name }},ether2"
        vlan-ids: 9
      - bridge: "{{ bridge_name }}"
        tagged: "{{ bridge_name }},ether2"
        vlan-ids: 99

- name: Create PPPoE Interface
  community.routeros.api_modify:
    path: interface pppoe-client
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    data:
      - name: pppoe-out
        interface: ether1
        user: "{{ nbn_username }}"
        password: "{{ nbn_password }}"
        add-default-route: true
        disabled: false
        max-mtu: 1492
        profile: default
        use-peer-dns: true
