---
- name: Mikrotik | API-Setup
  ansible.builtin.include_tasks: api-setup.yml
  when: api_status.stdout is not search('https-cert')

- name: Mikrotik | System Setup
  ansible.builtin.include_tasks: system.yml

- name: Mikrotik | Interfaces
  ansible.builtin.include_tasks: interfaces.yml

- name: Mikrotik | IPv6
  ansible.builtin.include_tasks: ipv6.yml

- name: Mikrotik | Wireguard
  ansible.builtin.include_tasks: wireguard.yml

- name: Mikrotik | Interface Lists
  ansible.builtin.include_tasks: interface-list.yml

- name: Mikrotik | Services
  ansible.builtin.include_tasks: services.yml

- name: Mikrotik | Graphing
  ansible.builtin.include_tasks: graphing.yml

- name: Mikrotik | Security Settings
  ansible.builtin.include_tasks: security.yml

- name: Mikrotik | IPv4 Address Lists
  ansible.builtin.include_tasks: address-lists-v4.yml

- name: Mikrotik | IPv4 FW Rules
  ansible.builtin.include_tasks: firewall-v4.yml

- name: Mikrotik | IPv6 Address Lists
  ansible.builtin.include_tasks: address-lists-v6.yml

- name: Mikrotik | IPv6 FW Rules
  ansible.builtin.include_tasks: firewall-v6.yml
