---
- name: Update Hostname
  community.routeros.api:
    path: system identity
    cmd: "set name={{ inventory_hostname }}"

- name: Set timezone
  community.routeros.api:
    path: system clock
    cmd: set time-zone-name=Australia/Perth

- name: Set Syslog Destination
  community.routeros.api_find_and_modify:
    path: system logging action
    find:
      name: remote
    values:
      remote: "{{ syslog_server }}"
      bsd-syslog: true

- name: Add Remote Topics
  community.routeros.api_modify:
    path: system logging
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    data:
      # Builtin Topics - Don't remove
      - action: echo
        topics: critical
      - action: memory
        topics: error
      - action: memory
        topics: info
      - action: memory
        topics: warning

      # Custom Topics
      - action: remote
        topics: critical
      - action: remote
        topics: error
      - action: remote
        topics: firewall
      - action: remote
        topics: info
      - action: remote
        topics: warning
