---
- name: Update Hostname
  community.routeros.api:
    path: system identity
    cmd: "set name={{ inventory_hostname }}"

- name: Set timezone
  community.routeros.api:
    path: system clock
    cmd: set time-zone-name=Australia/Perth

- name: Set Syslog Destination
  community.routeros.api_find_and_modify:
    path: system logging action
    find:
      name: remote
    values:
      remote: "{{ syslog_server }}"
      bsd-syslog: true

- name: Add Remote Topics
  community.routeros.api_modify:
    path: system logging
    data:
      - action: remote
        topics: critical
      - action: remote
        topics: error
      - action: remote
        topics: info
      - action: remote
        topics: warning
      - action: remote
        topics: firewall
