- name: Create Wireguard Interface
  community.routeros.api_modify:
    path: interface wireguard
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    data:
      - name: wireguard
        mtu: 1412 # when using PPPoE - https://www.hitoha.moe/wireguard-mtu-over-pppoe/
        listen-port: 51820

- name: Configure Wireguard IP address
  community.routeros.api_modify:
    path: ip address
    data:
      - interface: wireguard
        address: 172.16.32.1/24
        network: 172.16.32.0

- name: Configure Wireguard Peers
  community.routeros.api_modify:
    path: interface wireguard peers
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    data:
      - allowed-address: 172.16.32.2/32
        interface: wireguard
        comment: Colin Android
        public-key: LFezMEJ0eBCqLO9N7cE5wy7m9ardlMGcIWs65SexjX4=
      # - allowed-address: 172.16.32.3/32
      #  interface: wireguard
      #  comment:
      #  public-key:
      - allowed-address: 172.16.32.4/32
        interface: wireguard
        comment: Colin Fedora
        public-key: p6lGb3Jp8AoZkPQBxClwBKwyEX6gnu/+sNDvXV7qSQo=
      - allowed-address: 172.16.32.5/32
        interface: wireguard
        comment: Colin Windows 11
        public-key: JkPqQCwvgYO83W9Vn4rF2hhaAYQd+Zwvf/ZTUFW141E=
      - allowed-address: 172.16.32.6/32
        interface: wireguard
        comment: Tash Laptop
        public-key: xvts1rtQVFG19AmsGIJaA440OD4e9S07xqq/RXLjc2s=
      - allowed-address: 172.16.32.7/32
        interface: wireguard
        comment: Tash iPhone
        public-key: TZs58GERbOLsNYkDQvLBhZ23rvM+RT9Jv70yNoRNh20=
